### ISSUE TITLE
Bridge vlan constants look incorrect

### ISSUE THREAD

**Issue by pdtilton** [rust-netlink/netlink-packet-route#8]
The constants for bridge vlan info at https://github.com/rust-netlink/netlink-packet-route/blob/main/src/rtnl/constants.rs#L412 look incorrect when compared to the values in the Linux uapi at https://elixir.bootlin.com/linux/v4.8/source/include/uapi/linux/if_bridge.h#L126.

The correct values should be:

pub const BRIDGE_VLAN_INFO_PVID: u16 = 2;
pub const BRIDGE_VLAN_INFO_UNTAGGED: u16 = 4;
pub const BRIDGE_VLAN_INFO_RANGE_BEGIN: u16 = 8;
pub const BRIDGE_VLAN_INFO_RANGE_END: u16 = 16;

**Comment by cathay4t** [comment]
Fixed by https://github.com/rust-netlink/netlink-packet-route/pull/15

**Comment by cathay4t** [comment]
Thanks  for the bug report! This has been fixed by crates.io release 0.14.1
