### ISSUE TITLE
useful constants being removed in the API rework? 

### ISSUE THREAD

**Issue by Luap99** [rust-netlink/netlink-packet-route#88]
I cannot find MACVLAN_MODE_BRIDGE and the other MACVLAN_MODE_ constants in 0.18 

I am not sure why they have been removed, callers need them to set a useful mode InfoMacVlan::Mode(), without it I have to define them in my code which seems much worse than having one definition here?

**Comment by Luap99** [comment]
Assuming we want to make a type safe API it would properly make more sense for InfoMacVlan::Mode() to be an enum with the available modes like it is defined in the kernel instead of accepting a u32.
```
enum macvlan_mode {
	MACVLAN_MODE_PRIVATE = 1, /* don't talk to other macvlans */
	MACVLAN_MODE_VEPA    = 2, /* talk to other ports through ext bridge */
	MACVLAN_MODE_BRIDGE  = 4, /* talk to bridge ports directly */
	MACVLAN_MODE_PASSTHRU = 8,/* take over the underlying device */
	MACVLAN_MODE_SOURCE  = 16,/* use source MAC address list to assign */
};
```

**Comment by isomer** [comment]
I can't find where RTNLGRP_* went in the refactor.  They appear to still be needed for `add_membership()`.

**Comment by cathay4t** [comment]
Let me introduce it back as enum.

**Comment by cathay4t** [comment]
https://github.com/rust-netlink/netlink-packet-route/pull/95

**Comment by cathay4t** [comment]
The enum is `MacVlanMode` and `MacVtapMode`.

Instead of use `repr[u32]` and hard code value to enum entry, I implemented `From<u32>`. This is to be consist with other enum which originally designed to hold different integer value on non-linux platform.
