### ISSUE TITLE
Panic on kernel version <4.6

### ISSUE THREAD

**Issue by itsxaos** [rust-netlink/netlink-packet-route#96]
What versions of the kernel are supported by the rust-netlink crates?

I'm asking because I was unable to find this information anywhere and I ran into an issue on kernel 4.4.
Specifically, the connection task panics trying to parse [`netlink_packet_route::link::Stats`], because the [`rx_nohandler`] field does not exist (`thread 'tokio-runtime-worker' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/netlink-packet-route-0.19.0/src/link/stats.rs:61:1:
range end index 96 out of range for slice of length 92`).
This field was added in kernel 4.6 (see torvalds/linux@6e7333d3 or compare [`if_link.h` in 4.5] and [`if_link.h` in 4.6]).

[`netlink_packet_route::link::Stats`]: https://docs.rs/netlink-packet-route/latest/netlink_packet_route/link/struct.Stats.html
[`rx_nohandler`]: https://docs.rs/netlink-packet-route/latest/netlink_packet_route/link/struct.Stats.html#structfield.rx_nohandler
[`if_link.h` in 4.5]: https://elixir.bootlin.com/linux/v4.5/source/include/uapi/linux/if_link.h
[`if_link.h` in 4.6]: https://elixir.bootlin.com/linux/v4.6/source/include/uapi/linux/if_link.h

**Comment by cathay4t** [comment]
Sorry for the problem!

I was coding it using 6.6. :) 

But we should provide backwards compatibility, so let me fix it in my coming holiday.

**Comment by itsxaos** [comment]
Awesome, thank you!

**Comment by cathay4t** [comment]
Anyone what to help could just patch `buffer!` macro in `netlink-packet-utils` to auto extend if buffer is too small. This should solve all similar problem once for all.

**Comment by cathay4t** [comment]
@itsxaos Could you review https://github.com/rust-netlink/netlink-packet-route/pull/97 and try it in your system?
