### ISSUE TITLE
`#[non_exhaustive]` on structs makes some types impossible to create

### ISSUE THREAD

**Issue by little-dude** [rust-netlink/netlink-packet-route#99]
I just ran into this while trying to create a next-hop attribute:

```
error[E0639]: cannot create non-exhaustive struct using struct expression
   --> flockd/src/netlink_writer.rs:121:36
    |
121 |                       next_hops.push(RouteNextHop {
    |  ____________________________________^
122 | |                         flags: vec![],
123 | |                         hops: 0,
124 | |                         interface_index: intf_id.into(),
125 | |                         attributes: vec![RouteAttribute::Gateway(addr.into())],
126 | |                     });
    | |_____________________^
```

And indeed the `RouteNextHop` struct is decorated with a `#[non_exhaustive]` attribute.

```rust
#[derive(Debug, Clone, Eq, PartialEq, Default)]
#[non_exhaustive]
pub struct RouteNextHop {
    /// Next-hop flags
    pub flags: Vec<RouteNextHopFlag>,
    /// Next-hop priority
    pub hops: u8,
    /// Interface index for the next-hop
    pub interface_index: u32,
    /// Attributes
    pub attributes: Vec<RouteAttribute>,
}
```

I understand that backward compatibility is an issue, but using this on structs makes them partially useless. Should we get rid of this attribute on structs at least?

**Comment by cathay4t** [comment]
If you are sure kernel will never add new member, you may remove the `non_exhaustive`, otherwise, please
either use `RouteNextHop::default()` or introduce `RouteNextHop::new(flags, hops, interface_index, attributes)`.

**Comment by little-dude** [comment]
The kernel doesn't make such guarantees I think. Still, I'd like to be able to construct a struct the "natural" way. I feel like if we ever have to change this struct, we can just bump our version, and users can fix their code when they upgrade. Could we simply remove the `non_exhaustive`?

**Comment by ydirson** [comment]
@little-dude that's where constructors are useful in Rust :)

but when new parameters may be added in the future, we will require a new ctor (pun intended), so @cathay4t do we want to use `new()` for this particular signature and maybe add `new2()` or `new5()` when a 5th field gets added?  Maybe an explicit convention for this would be useful?

**Comment by little-dude** [comment]
By constructors do you mean the `new`-like methods? They can be used for many things, but in this case, I don't find it very pleasant to use:

```rust
RouteNextHop::new(vec![], 1, 1, vec![])
```
vs

```rust
RouteNextHop {
    flags: vec![],
    hops: 1,
    interface_index: 1,
    attributes: vec![],
}
```

In the first case it's very unclear what the arguments correspond to. In the second case it's explicit. At it gets worse as the number of fields increases. At some point you'll need a builder struct if you want to keep things readable.

---

I'm also not a fan of the `new()`, `new1()`, approach to preserve backward compatibility. We'd end up with a bloated API pretty fast if we did that with all the types we expose. Instead, why not just accept to make breaking changes and bump the crate version? That's exactly what semver is for.

**Comment by ydirson** [comment]
> why not just accept to make breaking changes and bump the crate version? That's exactly what semver is for.

Because it creates a breaking change that requires changes in user code, which should be avoided if possible (and yes, Cargo makes it too easy), especially when providing a wrapper for an API that does provide backward compatibility.

> In the first case it's very unclear what the arguments correspond to. In the second case it's explicit.

True.  A builder pattern surely allows to make that more explicit, but then I'm not sure there is a zero-cost builder pattern.  They don't really discuss this aspect in the [builder pattern description](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html)

**Comment by ydirson** [comment]
Thinking twice about it, we likely don't need a real builder anyway.  A `Default` impl (or a `new()` with most-used fields if applicable) and a few (inline) chainable setters could be a good option?

**Comment by little-dude** [comment]
> Because it creates a breaking change that requires changes in user code, which should be avoided if possible (and yes, Cargo makes it too easy), especially when providing a wrapper for an API that does provide backward compatibility.

I disagree with the fact that breaking changes are undesirable. As you say, cargo makes them easy to handle, so imo avoiding version bumps does not justify going for an API that is less convenient. Moreover, the rtnetlink API is pretty stable, it's been there for many years already and apart from some niche types, it hasn't had significant NBC changes lately afaik.


> True. A builder pattern surely allows to make that more explicit, but then I'm not sure there is a zero-cost builder pattern. They don't really discuss this aspect in the [builder pattern description](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html)

Agree. I don't think we should provide builders.

> A Default impl (or a new() with most-used fields if applicable) and a few (inline) chainable setters could be a good option?

Imo it's quite a lot of additional code to maintain if we're doing this for every struct. As a user, I might also forget to set a field since they are initialized for me. So my preference would still be to just accept to _maybe_ one day make a non backward compatible change.

**Comment by hellow554** [comment]
sure, of course ;)

But your sample code implemented `Default` and I think it's not a big deal to implement `Default` for all types that are provided

**Comment by cathay4t** [comment]
The `..Default::default()` will not work if the struct is from a external crate. It only works within crate.

Breaking API is pain to me as my projects use rust-netlink extensively, I do not want to modify my code everytime something new added to a struct/enum.

Unless rust-lang provide good solution to this, I intend to be the bad guy on preferring API stable than convenience.

There is pre-RFC discussion about `Default` trait on `[non_exhaustive]`: https://internals.rust-lang.org/t/pre-rfc-relaxed-non-exhaustive-structs/11977/18

**Comment by cathay4t** [comment]
Currently, I guess the only way to initialize a non_exhaustive struct is:

```rust
let mut a = Foo::default();
a.b = 1.5;
```

**Comment by little-dude** [comment]
@cathay4t I know that's the only way. My point is that this is too restrictive, and that backward compatibility concerns are not a strong enough reason to justify such a limitation because:

- rust tooling makes handling NBC changes very easy
- the `rtnetlink` API in linux is quite stable anyway

I haven't seen counter arguments for these two points. @ydirson even [acknowledged that NBC upgrades are not problematic in Rust](https://github.com/rust-netlink/netlink-packet-route/issues/99#issuecomment-1968989600).

So far the discussion has mostly been about working around the limitations of this API (having multiple `new` methods, providing a builder, using `Default`), but none of them is satisfactory imo.

**Comment by ydirson** [comment]
> I haven't seen counter arguments for these two points. @ydirson even [acknowledged that NBC upgrades are not problematic in Rust](https://github.com/rust-netlink/netlink-packet-route/issues/99#issuecomment-1968989600).

This is confusing, you say "NBC" ("non-breaking change" I guess?) but seem to talk about breaking changes.

If my understanding of what you say is correct, that's exactly the opposite of what I wrote with "which should be avoided if possible (and yes, Cargo makes it too easy)".  You do not explain why you think the fact that making a breaking change has been made *easy to make* is an excuse to make some, while they will always by nature require work from downstream crates, needlessly eating developer time.

**Comment by little-dude** [comment]
I was referring to this portion:

> and yes, Cargo makes it too easy

> You do not explain why you think the fact that making a breaking change has been made easy to make is an excuse to make some

I did explain that several time but I'll repeat here: because in this specific case, allowing breaking changes allows us to expose a better API

>  while they will always by nature require work from downstream crates, needlessly eating developer time.

That's the nature of software. People who don't want to spend time upgrading can stay on old versions.

**Comment by little-dude** [comment]
> Currently, I guess the only way to initialize a non_exhaustive struct is:
> 
> ```rust
> let mut a = Foo::default();
> a.b = 1.5;
> ```

As I've said previously, the big downside with that it's very easy to forget some fields, and spend time debugging why the kernel rejects a message.

---

Anyway I guess there's no point arguing further. We clearly have different opinions about the trade-offs of stability vs APIs. If that `non_exhaustive` is to be generalized I'll just stick to a fork.

**Comment by ydirson** [comment]
> People who don't want to spend time upgrading can stay on old versions.

This ignores the fact that "staying on old version" most of the time means no security fixes.  The very fact Cargo makes it easy to handle breaking changes leaves maintainers abusing it with many versions that would need to be supported, so maintainers who care will limit breaking changes.

**Comment by little-dude** [comment]
And how many security fixes has this crate had over the past 4 gtg?
